### ISSUE TITLE
walkthrough on local copy to identify issues

### ISSUE THREAD

**Issue by momokokong** [justkuper/Nestify#104]

**Comment by justkuper** [comment]
for me: user profile doesnt update

**Comment by arturoa925** [comment]
check out update profile functions for user and provider

**Comment by arturoa925** [comment]
create a default value for date ui when creating a ticket; right now clicking a date is mandatory for date value to be set

**Comment by justkuper** [comment]
when viewing ticket details, the buttons turn back into signup/login
