### ISSUE TITLE
Initiate file structure

### ISSUE THREAD

**Issue by momokokong** [justkuper/Nestify#2]
MVC model with M - postgres and sequelize, V- handlebars, and C - node express.

root
- config/
-- connection.js
- controllers/
-- api/
- db/
-- schema.sql
- models/
- public/
-- css/ 
-- js/
- seeds/
- utils/
- views/
-- layouts/
-- partials/
- .gitignore
- package.json
- README.md
- server.js

**Comment by justkuper** [comment]
add to .env
